name: vitalact
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  video_player: ^2.9.2
  animations: ^2.0.11
  permission_handler: ^12.0.1
  camera: ^0.12.0+1
  firebase_ai: ^3.11.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flutter_unity_widget: ^2022.2.1
  flutter:
    sdk: flutter
  gradient_borders: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/spritesheet/
    - assets/spritesheet/50_frames/
    - assets/data/
    - assets/videos/

  fonts:
    - family: BalooBhai2
      fonts:
        - asset: assets/fonts/BalooBhai2-Semibold.ttf
          weight: 600
        - asset: assets/fonts/BalooBhai2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooBhai2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooBhai2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BalooBhai2-Bold.ttf
          weight: 700
